### ISSUE TITLE
Malformed boolean value not detected

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#87] opened 2019-09-17 19:22 UTC
# Subject of the issue

A malformed boolean value is not correctly detected.

# Steps to reproduce

Insert a boolean value in a malformed way, such as `fals`, then upload the file.

# Expected behaviour

The editor should catch it and do something (notify the user?).

# Actual behaviour

Nothing happens and the wrong value stays there.

**Comment by sebbalex** [comment] 2020-06-05 14:40
This should be considered closed as of #103 but I keep it open since the issue is not resolved at all. Now supplying such malformed boolean values Editor will totally crash.

**Comment by bfabio** [comment] 2020-12-09 11:00
Now we show an empty error:
![image](https://user-images.githubusercontent.com/788293/101621310-e2e03200-3a15-11eb-903a-ed679103bc9b.png)

The validator returns:
`[{"Key":"it/conforme/gdpr","Reason":"Unexpected string key"}]`

**Closed** 2021-01-19 08:40 UTC
Labels: bug
