### ISSUE TITLE
The editor prints a <200b> at the end of the longDescription field

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#56] opened 2019-04-03 17:44 UTC
# Subject of the issue

The editor prints a <200b> at the end of the `longDescription` field (in the resulting publiccode.yml file).
It happened me twice.

I will investigate further how to correctly reproduce this.

**Comment by libremente** [comment] 2019-10-02 16:10
What should we do with this issue? @sebbalex

**Comment by sebbalex** [comment] 2020-06-09 15:14
@libremente this should be fixed now, can you confirm?

**Comment by bfabio** [comment] 2023-06-23 09:33
Can't reproduce, feel free to reopen this

**Closed by bfabio** 2023-06-23 09:33 UTC
Labels: bug, needs-triage
